- name: Destroy Instance of Digital Ocean Droplet  
  hosts: localhost
  vars_files: 
    - ../machines.yml
  tasks: 
    - name: "Check if SSH keys exist "
      stat: 
        path : "~/.ssh/id_rsa"
      register: ssh_key
    - name: "Create SSH keys when it does not exist "
      command: ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
      when: not ssh_key.stat.exists
    - name: "Loading the public key"
      command: cat ~/.ssh/id_rsaa.pub
      register: master_public_key
    - name: Show the public key
      debug: 
        msg: "{{ master_public_key.stdout }}"
    - name: "Create Droplet"
      community.digitalocean.digital_ocean_droplet:
        state: absent
        name: "{{ item.name }}"
        api_token: "{{ auth_token }}"    # Note: changed oauth_token to api_token
        size: "{{ item.size }}"
        region: "{{ item.region }}"
        image: "{{ item.image }}"
        wait_timeout: 500
        user_data: |
          #cloud-config
          users:
            - name: tra
              shell: /bin/bash
              ssh_authorized_keys:
                - "{{ master_public_key.stdout }}"
      loop: "{{ machines }}"
      register: droplets